---
title: "Installing Packages and Visualizing the Iris Dataset"
output: html_document
---

Coursera IBM Data Scicence

Course 2 Tools for Data Science

Module M5 RStudio & GitHub

Plotting with RStudio

```{r all-code, include=TRUE}
# Install required packages (run manually if needed)
# Ensure that these lines are run only once and commented out afterward to avoid reinstallation
# install.packages("labelled")
# install.packages("https://cran.r-project.org/src/contrib/Archive/patchwork/patchwork_1.1.0.tar.gz", 
#                  repos = NULL, type = "source", dependencies = TRUE)
# install.packages("https://cran.r-project.org/src/contrib/Archive/broom.helpers/broom.helpers_1.4.0.tar.gz", 
#                  repos = NULL, type = "source", dependencies = TRUE)
# install.packages("https://cran.r-project.org/src/contrib/Archive/ggstats/ggstats_0.5.0.tar.gz", 
#                  repos = NULL, type = "source", dependencies = TRUE)
# install.packages("GGally")

# Load the datasets library
library(datasets)

# Load the iris dataset
data(iris)

# Display the first few rows of the dataset
head(iris)

# Load the GGally library
library(GGally)

# Create a pairwise plot
ggpairs(iris, mapping = ggplot2::aes(colour = Species))
